services:
  db:
    image: postgres
    ports:
      - '15432:5432'
    environment:
      POSTGRES_USER: passdev
      POSTGRES_PASSWORD: Qwerty1@456
      POSTGRES_DB: passport-db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U passdev -d passport-db']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
